# Generated by Django 3.1 on 2020-08-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_date', models.CharField(max_length=10)),
                ('court_time', models.CharField(max_length=8)),
                ('court_number', models.IntegerField(max_length=1)),
                ('court_play', models.BooleanField()),
                ('comments', models.TextField(max_length=200)),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('player3', models.CharField(max_length=50)),
                ('player4', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
