# Generated by Django 3.1 on 2020-08-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200812_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisbooking',
            name='player3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tennisbooking',
            name='player4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
