# Generated by Django 3.1 on 2020-08-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200812_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_date', models.CharField(max_length=10)),
                ('news_time', models.CharField(max_length=8)),
                ('news_body', models.TextField()),
                ('news_readtime', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
